### PR TITLE
fix fopen FILE* unsigned comparison bug 

### PR DESCRIPTION
**Pull request by pnfisher**
iotc_bsp_io_fs_open()

src/bsp/platform/posix/iotc_bsp_io_fs_posix.c

sets resource_handle_out to the FILE* returned by fopen() if fopen()
doesn't fail. This in turn gets assigned to the resource manager's
context->resource_handle. Later, iotc_resource_manager_read() in

src/libiotc/io/fs/iotc_resource_manager.c

checks to make sure context->resource_handle is not less the
zero. But there's nothing about fopen() that ensures that the FILE*
returned by fopen() can't be a value less than zero (when used in a
signed comparison).

If iotc_resource_manager_read() is going to assume a value less than
0 indicates a BSP file io open error, then we need to replace the use
of fopen() in iotc_bsp_io_fs_posix.c with open().

#72

### CODE REVIEW

**Comment by pnfisher** [comment]
@googlebot I signed it!

**Comment by pnfisher** [comment]
Point of Contact: jordanc@ecobee.com
Google group: google-contributors@ecobee.com

**Comment by gguuss** [comment]
Code is LGTM but I'm not seeing you as having signed the CLA with the account `pnfisher`.  Make sure you've added it here https://cla.developers.google.com with the email / username associated with your GitHub account.

**Comment by pnfisher** [comment]
@gguuss Sorry, but I'm supposed to be part of an employee group.

google-contributors@ecobee.com.

Am I still supposed to sign as an individual contributor even though I'm part of the above employer group? I've added my work email (philipf@ecobee.com) to my account and was told by my employer that that should be sufficient to complete the CLA signing process.

**Comment by gguuss** [comment]
@pnfisher I just need to verify the GitHub account / email associated with the GH account has signed and then should be able to set the CLA signed bit. If you enter your GitHub/email [on this page](https://cla.developers.google.com/clas) that should cover you.

**Comment by pnfisher** [comment]
@gguuss Sorry for being a bit dense. But which email should I enter on this page (https://cla.developers.google.com/clas)? My ecobee work email (philipf@ecobee.com) or my primary github email (philipnfisher@gmail.com)? And should I just enter it using the "Only Yourself" CLA link?

**Comment by gguuss** [comment]
Super sorry for all the friction here :(

Put in philipf@ecobee.com and your GitHub username and we should be good to go. Having only yourself should be fine.

If there's still an issue, I can reach out internally and see if I can consider you manually verified and just not showing up in our system.

**Comment by pnfisher** [comment]
@gguuss Okay, I've signed/entered my work email (philipf@ecobee.com) in the CLA form. (Or at least, I think I have.)

**Comment by gguuss** [comment]
Woohoo! It worked!

**Comment by gguuss** [comment]
Merging, thanks for your contribution!

**Pull request merged**
